# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MrBird's blog
subtitle: 
description:
author: MrBird
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment #部署，将 lmintlcx 改成用户名
deploy:
  type: git
  repo: https://github.com/wuyouzhuguli/wuyouzhuguli.github.io.git
  username: wuyouzhuguli
  email: 852252810@qq.com
  branch: master

# Extensions
## Plugins: http://hexo.io/plugins/
plugins: hexo-generate-feed

server:
  port: 4001
  compress: true
  header: true
  
index_generator:
  per_page: 5

archive_generator:
  per_page: 30
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
marked:
  gfm: true
  breaks: false

# hexo-admin authentification
admin:
  username: wuyouzhuguli
  password_hash: $2a$10$5Dy/DYm9iaLv2rpk4Oc7D.RqneViK8YCiPeohzj8S2oBim/W3GheS
  secret: my super secret phrase